using Content.Shared.CartridgeLoader.Cartridges; // Ensure this points to where your enums are!
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class BadgePrintUiFragment : BoxContainer
{
    public event Action<SelectedBadgeTimer, SelectedDepartment>? OnPrintPressed;

    public SelectedBadgeTimer SelectedTime { get; private set; } = SelectedBadgeTimer.Print5;
    public SelectedDepartment SelectedDept { get; private set; } = SelectedDepartment.All;

    public BadgePrintUiFragment()
    {
        RobustXamlLoader.Load(this);

        // --- TIME BUTTONS SETUP ---
        Button5Min.ToggleMode = true;
        Button10Min.ToggleMode = true;
        Button15Min.ToggleMode = true;
        Button25Min.ToggleMode = true;

        Button5Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print5);
        Button10Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print10);
        Button15Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print15);
        Button25Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print25);

        // --- DEPARTMENT BUTTONS SETUP ---
        AllAccess.ToggleMode = true;
        BridgeAccess.ToggleMode = true;
        SecurityAccess.ToggleMode = true;
        MedicalAccess.ToggleMode = true;
        EngineeringAccess.ToggleMode = true;
        ScienceAccess.ToggleMode = true;
        CargoAccess.ToggleMode = true;
        ServiceAccess.ToggleMode = true;

        AllAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.All);
        BridgeAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Bridge);
        SecurityAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Security);
        MedicalAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Medical);
        EngineeringAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Engineering);
        ScienceAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Science);
        CargoAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Cargo);
        ServiceAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Service);

        // --- PRINT BUTTON ---
        Print.OnPressed += _ => OnPrintPressed?.Invoke(SelectedTime, SelectedDept);

        // Set the initial default states
        SetActiveTime(SelectedBadgeTimer.Print5);
        SetActiveDepartment(SelectedDepartment.All);
    }

    private void SetActiveTime(SelectedBadgeTimer timer)
    {
        SelectedTime = timer;

        Button5Min.Pressed = (timer == SelectedBadgeTimer.Print5);
        Button10Min.Pressed = (timer == SelectedBadgeTimer.Print10);
        Button15Min.Pressed = (timer == SelectedBadgeTimer.Print15);
        Button25Min.Pressed = (timer == SelectedBadgeTimer.Print25);
    }

    private void SetActiveDepartment(SelectedDepartment department)
    {
        SelectedDept = department;

        AllAccess.Pressed = (department == SelectedDepartment.All);
        BridgeAccess.Pressed = (department == SelectedDepartment.Bridge);
        SecurityAccess.Pressed = (department == SelectedDepartment.Security);
        MedicalAccess.Pressed = (department == SelectedDepartment.Medical);
        EngineeringAccess.Pressed = (department == SelectedDepartment.Engineering);
        ScienceAccess.Pressed = (department == SelectedDepartment.Science);
        CargoAccess.Pressed = (department == SelectedDepartment.Cargo);
        ServiceAccess.Pressed = (department == SelectedDepartment.Service);
    }

    public void UpdateState() // Removed unused news arguments
    {
        // Update state logic here if needed by the server
    }
}
