using Content.Shared.Access;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class BadgePrintUiFragment : BoxContainer
{
    public event Action<SelectedBadgeTimer, SelectedDepartment>? OnPrintPressed;

    public SelectedBadgeTimer SelectedTime { get; private set; } = SelectedBadgeTimer.Print5;
    public SelectedDepartment SelectedDept { get; private set; } = SelectedDepartment.All;

    public BadgePrintUiFragment()
    {
        RobustXamlLoader.Load(this);

        // --- TIME BUTTONS SETUP ---
        Button5Min.ToggleMode = true;
        Button10Min.ToggleMode = true;
        Button15Min.ToggleMode = true;
        Button25Min.ToggleMode = true;

        Button5Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print5);
        Button10Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print10);
        Button15Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print15);
        Button25Min.OnPressed += _ => SetActiveTime(SelectedBadgeTimer.Print25);

        // --- DEPARTMENT BUTTONS SETUP ---
        AllAccess.ToggleMode = true;
        CommandAccess.ToggleMode = true;
        SecurityAccess.ToggleMode = true;
        MedicalAccess.ToggleMode = true;
        EngineeringAccess.ToggleMode = true;
        ResearchAccess.ToggleMode = true;
        CargoAccess.ToggleMode = true;
        ServiceAccess.ToggleMode = true;

        AllAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.All);
        CommandAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Command);
        SecurityAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Security);
        MedicalAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Medical);
        EngineeringAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Engineering);
        ResearchAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Research);
        CargoAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Cargo);
        ServiceAccess.OnPressed += _ => SetActiveDepartment(SelectedDepartment.Service);

        // --- PRINT BUTTON ---
        Print.OnPressed += _ => OnPrintPressed?.Invoke(SelectedTime, SelectedDept);

        // Set the initial default states
        SetActiveTime(SelectedBadgeTimer.Print5);
        SetActiveDepartment(SelectedDepartment.All);
    }

    /// <summary>
    /// Grays out access buttons that the player does not have.
    /// </summary>
    public void UpdateAccess(ICollection<ProtoId<AccessLevelPrototype>> accesses)
    {
        var all = accesses.Contains(new("Captain"));
        var command = accesses.Contains(new("Command"));
        var sec = accesses.Contains(new("Security"));
        var med = accesses.Contains(new("Medical"));
        var eng = accesses.Contains(new("Engineering"));
        var sci = accesses.Contains(new("Research"));
        var cargo = accesses.Contains(new("Cargo"));
        var srv = accesses.Contains(new("Service"));

        AllAccess.Disabled = !all;
        CommandAccess.Disabled = !command;
        SecurityAccess.Disabled = !sec;
        MedicalAccess.Disabled = !med;
        EngineeringAccess.Disabled = !eng;
        ResearchAccess.Disabled = !sci;
        CargoAccess.Disabled = !cargo;
        ServiceAccess.Disabled = !srv;

        // Select first available department
        if (all) SetActiveDepartment(SelectedDepartment.All);
        else if (command) SetActiveDepartment(SelectedDepartment.Command);
        else if (sec) SetActiveDepartment(SelectedDepartment.Security);
        else if (med) SetActiveDepartment(SelectedDepartment.Medical);
        else if (eng) SetActiveDepartment(SelectedDepartment.Engineering);
        else if (sci) SetActiveDepartment(SelectedDepartment.Research);
        else if (cargo) SetActiveDepartment(SelectedDepartment.Cargo);
        else if (srv) SetActiveDepartment(SelectedDepartment.Service);
        else Print.Disabled = true; // Disable printing if no accesses match
    }

    private void SetActiveTime(SelectedBadgeTimer timer)
    {
        SelectedTime = timer;

        Button5Min.Pressed = (timer == SelectedBadgeTimer.Print5);
        Button10Min.Pressed = (timer == SelectedBadgeTimer.Print10);
        Button15Min.Pressed = (timer == SelectedBadgeTimer.Print15);
        Button25Min.Pressed = (timer == SelectedBadgeTimer.Print25);
    }

    private void SetActiveDepartment(SelectedDepartment department)
    {
        SelectedDept = department;

        AllAccess.Pressed = (department == SelectedDepartment.All);
        CommandAccess.Pressed = (department == SelectedDepartment.Command);
        SecurityAccess.Pressed = (department == SelectedDepartment.Security);
        MedicalAccess.Pressed = (department == SelectedDepartment.Medical);
        EngineeringAccess.Pressed = (department == SelectedDepartment.Engineering);
        ResearchAccess.Pressed = (department == SelectedDepartment.Research);
        CargoAccess.Pressed = (department == SelectedDepartment.Cargo);
        ServiceAccess.Pressed = (department == SelectedDepartment.Service);
    }
}
